# Generated by Django 5.0.3 on 2024-03-23 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dataentry', '0002_employee'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('country', models.CharField(max_length=255)),
            ],
        ),
        migrations.AlterField(
            model_name='employee',
            name='name',
            field=models.CharField(max_length=250),
        ),
    ]
